#!/usr/bin/env python

import sys

sys.path.extend(("../src", "../tests"))

import pygtk

pygtk.require("2.0")

import gtk
import cairo
import pango
import os

DEFAULT_BUFFER = """\
# This is a Python script to quickly test Cairo stuff!
# You have access to the following variables:
# cr = The Cairo drawing context.
# W  = The DrawingArea's allocated width.
# H  = The DrwaingArea's allocated height.

import math

cr.set_line_width(10)
cr.arc(w / 2.0, h / 2.0, h / 3.0, 0.0, 2.0 * math.pi)
cr.set_source_rgb(0.3, 0.3, 0.3)
cr.fill_preserve()
cr.set_source_rgb(0.1, 0.1, 0.1)
cr.stroke()
"""

class CairoDrawingArea(gtk.DrawingArea):
	def __init__(self, width=0, height=0, win=None, buf=DEFAULT_BUFFER):
		gtk.DrawingArea.__init__(self)

		self._buffer = buf
		self._win    = win

		self.set_size_request(width, height)
		
		self.connect("expose-event", self._render)

	def _render(self, widget, event):
		c    = self.window.cairo_create()
		w, h = self.allocation.width, self.allocation.height

		if self._win:
			self._win.set_status(w, h)

		self._eval(self._buffer, c, w, h)

		return True

	def _eval(self, buf, cr, w, h):
		eval(compile(buf, "<cairoscript>", "exec"), {
			"cr": cr,
			"w":  w,
			"h":  h
		})

	def _set_width_and_height(self, w, h):
		if not w:
			w = self.allocation.width
		
		if not h:
			h = self.allocation.height
	
		return int(w), int(h)

	def parse(self, buf):
		self._buffer = buf

		self.queue_draw()

	def write_to_png(self, path, w=None, h=None):
		w, h = self._set_width_and_height(w, h)
		
		surface = cairo.ImageSurface(cairo.FORMAT_ARGB32, w, h)
		context = cairo.Context(surface)

		self._eval(self._buffer, context, w, h)

		surface.write_to_png(path)

	def write_to_svg(self, path, w=None, h=None):
		w, h = self._set_width_and_height(w, h)

		surface = cairo.SVGSurface(path, w, h)
		context = cairo.Context(surface)

		self._eval(self._buffer, context, w, h)

		surface.flush()
		surface.finish()

class TextView(gtk.TextView):
	def __init__(self, text=""):
		gtk.TextView.__init__(self)

		buf = gtk.TextBuffer()

		buf.set_text(text)

		self.set_buffer(buf)
		self.set_size_request(-1, 300)
		self.connect("realize", self._realize)

	def _realize(self, *args):
		self.set_font_size(10)

	def set_text(self, text):
		self.get_buffer().set_text(text)

	def set_font_size(self, size):
		font = pango.FontDescription("Droid Sans Mono")

		font.set_size(pango.SCALE * size)

		self.modify_font(font)

	def get_text(self):
		buf = self.get_buffer()
		
		return buf.get_text(buf.get_start_iter(), buf.get_end_iter())

class CairoWindow(gtk.Window):
	def __init__(self, w, h, script=None, autosave=None):
		gtk.Window.__init__(self, gtk.WINDOW_TOPLEVEL)

		b = script and open(script).read() or DEFAULT_BUFFER

		self._draw   = CairoDrawingArea(w, h, self, b)
		self._text   = TextView(b)
		self._status = gtk.Statusbar()

		tool   = gtk.HBox()
		vbox   = gtk.VBox()
		scroll = gtk.ScrolledWindow()
		paned  = gtk.VPaned()
		frame  = gtk.Frame()

		scroll.set_policy(gtk.POLICY_AUTOMATIC, gtk.POLICY_AUTOMATIC)
		scroll.add(self._text)

		frame.add(scroll)

		"""
		a = gtk.Alignment(0.5, 0.5)
		a.set_padding(10, 10, 10, 10)
		a.add(self._draw)
		"""

		paned.add1(self._draw)
		paned.add2(frame)

		vbox.pack_start(paned)
		vbox.pack_start(tool, False, False, 2)
		vbox.pack_start(self._status, False, False)

		for st, tt, cb in zip((
			gtk.STOCK_OPEN,
			gtk.STOCK_SAVE,
			gtk.STOCK_YES,
			gtk.STOCK_REFRESH,
			gtk.STOCK_QUIT
		), (
			"Open an existing script",
			"Save this script",
			"Write script to PNG/SVG images",
			"Refresh the DrawingArea",
			"Quit the application"
		), (
			self._open_script,
			self._save_script,
			self._save_image,
			self._parse_code,
			lambda *a, **k: gtk.main_quit()
		)):
			button = gtk.Button()
			image  = gtk.Image()

			image.set_from_stock(st, gtk.ICON_SIZE_MENU)

			button.set_relief(gtk.RELIEF_NONE)
			button.set_focus_on_click(False)
			button.set_image(image)
			button.set_tooltip_text(tt)
			button.connect("clicked", cb)
			
			tool.pack_start(button, False, False)

		fontSizeLabel = gtk.Label("Font Size:")
		fontSize      = gtk.combo_box_new_text()

		fontSizeLabel.set_alignment(1.0, 0.5)

		[fontSize.append_text("%i" % i) for i in range(8, 13)]

		fontSize.connect("changed", self._set_font)
		fontSize.set_active(2)

		tool.pack_start(fontSizeLabel, True, True, 5)
		tool.pack_start(fontSize, False, False)

		self.set_title("cairodraw")
		self.add(vbox)
		self.set_focus(self._text)

		if autosave:
			self._draw.queue_draw()
			self._save_image(None, w, h)

	def set_status(self, w, h):
		self._status.push(0, "Dimensions: %i x %i" % (w, h))

	def _open_script(self, *args):
		fc = gtk.FileChooserDialog(
			"Select a script file...",
			self,
			buttons=(gtk.STOCK_CANCEL, 0, gtk.STOCK_OPEN, 1)
		)

		fl1 = gtk.FileFilter()

		fl1.set_name("Pycairo Scripts")
		fl1.add_pattern("*.py")

		fl2 = gtk.FileFilter()

		fl2.set_name("All Files")
		fl2.add_pattern("*")

		fc.add_filter(fl1)
		fc.add_filter(fl2)

		if fc.run():
			self._text.set_text(open(fc.get_filename()).read())

			self._parse_code()

		fc.destroy()

	def _save_script(self, *args):
		fc = gtk.FileChooserDialog(
			"Save Python Script as...",
			self,
			gtk.FILE_CHOOSER_ACTION_SAVE,
			(gtk.STOCK_CANCEL, 0, gtk.STOCK_SAVE, 1)
		)

		if fc.run():
			fn = fc.get_filename()

			if not fn.endswith(".py"):
				fn += ".py"

			with open(fn, "w") as f:
				f.write(self._text.get_text())

		fc.destroy()

	def _save_image(self, widget, w=None, h=None):
		fc = gtk.FileChooserDialog(
			"Save PNG & SVG Images as...",
			self,
			gtk.FILE_CHOOSER_ACTION_SAVE,
			(gtk.STOCK_CANCEL, 0, gtk.STOCK_SAVE, 1)
		)

		if fc.run():
			self._draw.write_to_png(fc.get_filename() + ".png", w, h)
			self._draw.write_to_svg(fc.get_filename() + ".svg", w, h)

		fc.destroy()

	def _parse_code(self, *args):
		self._draw.parse(self._text.get_text())
	
	def _set_font(self, cb):
		self._text.set_font_size(int(cb.get_active_text()))

if __name__ == "__main__":
	f = None
	w = 512
	h = 256
	s = False

	if len(sys.argv) >= 2 and os.path.exists(sys.argv[1]):
		f = sys.argv[1]

	if len(sys.argv) >= 4:
		try:
			w = int(sys.argv[2])
			h = int(sys.argv[3])
			s = True

		except:
			pass

	cw = CairoWindow(w, h, f, s)

	if not s:
		cw.connect("destroy", gtk.main_quit)
		cw.show_all()

		gtk.main()
